### ISSUE TITLE
Madstream doesn't work properly

### ISSUE THREAD

**Issue by Govind-Rajulu** [LikDev-256/likdev256-tamil-providers#13]
The segments in site is wrongly showing as media.
The Mobile network's segment in the site opens to show channels whereas in the app it shows as a single stream.

Not sure about other providers. If possible check for all and confirm.

![Screenshot_20230225-165945](https://user-images.githubusercontent.com/41478619/221354529-296f92f6-0cd1-4cbb-8222-e86c262832ea.png)
![Screenshot_20230225-165949](https://user-images.githubusercontent.com/41478619/221354537-39b54264-432e-4595-80ef-91cd8a93838d.png)

**Comment by LikDev-256** [comment]
Scrapping is not that easy it's time consuming the site changes it's entire layout very often every time this happens the code should get rewritten. That's not going to be happening...
