### ISSUE TITLE
Tamildhool provider parent job is canceling 

### ISSUE THREAD

**Issue by sachienpk** [LikDev-256/likdev256-tamil-providers#14]
The Tamildhool provider is not working. The parent job is canceling. I am unable to find the issue 
![Screenshot_2023_0225_203224](https://user-images.githubusercontent.com/96417557/221357023-497c07ca-43cc-498f-9f58-f34382ac7a5e.jpg)
I have attached the screenshot of the problem. I'll be glad if you fix the problem. This is the troubleshoot of the problem. Hope it helps.

**Comment by LikDev-256** [comment]
It's fixed now, this the 3rd time in this week this crap broke

**Comment by sachienpk** [comment]
Yeah bro thanks BTW can you teach me how to make this repo based on our own needs. Coz,  the cloudstream documentation is quite confusing
