### ISSUE TITLE
Separate extension for Uhd movies 

### ISSUE THREAD

**Issue by venkat2305** [LikDev-256/likdev256-tamil-providers#15]
Would you please consider making a separate extension for Uhd movies. It's hit and miss on sorastream. Thanks

**Comment by venkat2305** [comment]
https://github.com/hexated/cloudstream-extensions-hexated/issues/115

**Comment by LikDev-256** [comment]
Done https://github.com/LikDev-256/likdev256-tamil-providers/commit/aa021a1197c7f275622f2b6b2fd8381bdbedb3f5 should have been downloaded by default automatically. Tv shows aren't still implemented though
