### ISSUE TITLE
Adding olamovies again  

### ISSUE THREAD

**Issue by aadio7** [LikDev-256/likdev256-tamil-providers#22]
Could you add ola movies again please...(idk why you disable it)

**Comment by LikDev-256** [comment]
For obvious reasons .... It has cloudflare enabled and requires login for downloads

**Comment by heliosII** [comment]
> For obvious reasons .... It has cloudflare enabled and requires login for downloads

Brother i have also two other website which dont have cloudflare i think so can you please check it
