### ISSUE TITLE
Bro I need Hindi dub anime extension

### ISSUE THREAD

**Issue by Mrunknow3** [LikDev-256/likdev256-tamil-providers#29]
I have already 3 repository animesaga and Animeworld not working and animeflix have not new dub. You can fix anime saga or you can add toonstream.in and any other good anime Hindi website. Pls

**Comment by karanveers969** [comment]
Your request has already been completed, check out animedekho from hexated repository

**Comment by Mrunknow3** [comment]
When I request animedekho not added bro after request added

**Comment by heliosII** [comment]
> When I request animedekho not added bro after request added

Close this issue then

**Comment by Mrunknow3** [comment]
Really I'm new on github idk how to close isse

**Comment by heliosII** [comment]
> Really I'm new on github idk how to close isse

Where you replying message .. See there is close issue option in down .. tap that
