### ISSUE TITLE
Live TV with Jwplayer 

### ISSUE THREAD

**Issue by phisher98** [LikDev-256/likdev256-tamil-providers#37]
https://madplay.live/hls/tata/

It is using jwplayer

Kindly add this it has live tv channels

jwplayer("jwplayerDiv").setup({ 'preload': "auto", 'stretching': "exactfit", 'width': "100%", 'height': "200", 'image': "http://imagestataplay.whatsonindia.com/dasimages/landscape/1280x720/7D7A5EBCA3D492DAA16454B6122030E5DC27EE4F5.jpg", 'logo': "http://imagestataplay.whatsonindia.com/dasimages/landscape/1280x720/7D7A5EBCA3D492DAA16454B6122030E5DC27EE4F5.jpg", file: "https://bpprod7linear.akamaized.net/bpk-tv/irdeto_com_Channel_307/output/manifest.mpd", type: "dash", drm: { "clearkey": { "keyId":"db6f1dbe0c005c2694914cca4791f6d5","key":"6f78f46833022785c8df240e5a13d94a" } }
});

**Comment by LikDev-256** [comment]
drm content is not yet playable as to my current knowledge of the app

**Comment by phisher98** [comment]
Hmmm okay @LikDev-256 snowflix still giving no links error
