### ISSUE TITLE
[Site Request] Bolly2Tolly

### ISSUE THREAD

**Issue by bachig26** [LikDev-256/likdev256-tamil-providers#4]
Main Domain: https://www.bolly2tolly.net

Alternate Domain: https://www.bolly2tolly.me

**Comment by LikDev-256** [comment]
Added by @daarkdemon [Daarkdemon's commit](https://github.com/daarkdemon/cs-darkdemon-extensions/commit/40488e27f60dd7d5a40e903ae3fdf42c859a60d8)
