### ISSUE TITLE
BanglaPlex Extension 

### ISSUE THREAD

**Issue by krishus96** [LikDev-256/likdev256-tamil-providers#50]
Extension isn't working. I use clone site feature because domain extension is changed and extension loads but still "No Links Found" error and no cover photo also.

Kindly Fix it. 👉｡⁠◕⁠‿⁠◕⁠｡👈

**Comment by phisher98** [comment]
@krishus96 Add Hindirepo shortcode to add Working one

**Comment by phisher98** [comment]
Already added in Hindirepo

**Comment by krishus96** [comment]
already added and updated and fixed and working in "Hindirepo" Plugin
